Repository codeceptjs/CodeceptJS, pull requests merged in 2019-11, with the labels that each got.

#2020 Improve headless chrome example
  docs/helpers/Protractor.md
  docs/helpers/WebDriver.md
  docs/helpers/WebDriverIO.md
  lib/helper/Protractor.js
  lib/helper/WebDriver.js
  lib/helper/WebDriverIO.js
Labels: documentation

#2031 Support remote connections for TestCafe helper
  docs/helpers/TestCafe.md
  lib/helper/TestCafe.js
  package.json
Labels: ready for merging, testcafe

#2038 fix: mismatch tags from title will cause null tag
  lib/ui.js
  test/unit/ui_test.js
Labels: WIP

#2041 fix(ts): FIx relative path for PageObject
  lib/command/definitions.js
  test/data/sandbox/configs/definitions/codecept.inject.po.json
  test/data/sandbox/configs/definitions/po/custom_steps.js
  test/runner/definitions_test.js
Labels: ready for merging

#2030 Finish Update of basics.md
  docs/basics.md
Labels: documentation

#2037 fix(#2026): Failed to read the 'localStorage' property from 'Window'
  lib/helper/Puppeteer.js
  test/helper/Puppeteer_test.js
Labels: ready for merging

#2044 improve the codeceptjs info
  bin/codecept.js
  lib/command/info.js
Labels: ready for merging

#2040 Fixed puppeteer grabhtml to refer to current context
  lib/helper/Puppeteer.js
  test/helper/Puppeteer_test.js
Labels: ready for merging

#2025 Runio scripts
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  RoboFile.php
  docs/changelog.md
  docs/community-helpers.md
  docs/helpers/ApiDataFactory.md
  docs/helpers/Appium.md
  docs/helpers/Detox.md
  docs/helpers/FileSystem.md
  docs/helpers/GraphQL.md
  docs/helpers/GraphQLDataFactory.md
  docs/helpers/MockRequest.md
  docs/helpers/Nightmare.md
  docs/helpers/Polly.md
  docs/helpers/Protractor.md
  docs/helpers/Puppeteer.md
  docs/helpers/REST.md
  docs/helpers/SeleniumWebdriver.md
  docs/helpers/TestCafe.md
  docs/helpers/WebDriver.md
  docs/helpers/WebDriverIO.md
  lib/helper/WebDriverIO.js
  package.json
  runio.js
Labels: deployment script

#2050 change docs generating command
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#2046 fix(docs): Incorrect types in docs for helpers
  .github/CONTRIBUTING.md
  docs/changelog.md
  docs/helpers/Appium.md
  docs/helpers/Nightmare.md
  docs/helpers/Protractor.md
  docs/helpers/Puppeteer.md
  docs/helpers/TestCafe.md
  docs/helpers/WebDriver.md
  docs/helpers/WebDriverIO.md
  docs/webapi/grabCookie.mustache
  package.json
  runio.js
Labels: WIP, documentation

#2049 Screenshots path correction
  lib/plugin/screenshotOnFail.js
  lib/utils.js
  test/unit/utils_test.js
Labels: ready for review
