Repository codeceptjs/CodeceptJS, pull requests merged in 2019-12, with the labels that each got.

#2057 fix: update JSDoc for `say`
  lib/output.js
Labels: ready for merging, typings

#2054 Streamlined return values from grab*
  lib/helper/WebDriver.js
Labels: webdriver

#2034 File system extended
  lib/helper/FileSystem.js
  test/unit/helper/FileSystem_test.js
Labels: file helper

#2059 fix: cannot grab for css attributes with hyphen
  lib/helper/Puppeteer.js
  lib/utils.js
  test/data/app/view/form/doubleclick.php
  test/helper/webapi.js
Labels: puppeteer

#2068 Docs/remove jsdoc extra line
  runio.js
  typings/types.d.ts
Labels: documentation, ready for review, typescript

#2064 fix: TestCafe grabAttributeFrom method not works
  .eslintignore
  lib/helper/TestCafe.js
  test/helper/webapi.js
Labels: ready for review, testcafe

#2043 #1911 - Regex for step Def file
  lib/container.js
Labels: ready for review

#2060 Allows overriding default Polly config in MockRequest
  lib/helper/MockRequest.js
Labels: puppeteer, webdriver

#2080 fix(docs): add info about _after hook in helper
  docs/helpers.md
Labels: documentation, ready for review

#2086 fix(docs): fix export information for pageobjects
  docs/pageobjects.md
  lib/helper/FileSystem.js
Labels: documentation, ready for review

#2087 Update custom helper docs
  docs/helpers.md
  docs/pageobjects.md
Labels: ready for review
