Repository codeceptjs/CodeceptJS, pull requests merged in 2020-01, with the labels that each got.

#2113 feat: add possibility to ignore doclet with 'ignore' and 'private' tags
  typings/jsdoc.namespace.js
Labels: dev, documentation, typescript

#2100 feat(todo|allure): Add method `todo` for planning on writing tests
  docs/basics.md
  docs/hooks.md
  lib/plugin/allure.js
  lib/ui.js
  package.json
  test/data/sandbox/configs/todo/codecept.conf.js
  test/data/sandbox/configs/todo/first_test.js
  test/runner/todo_test.js
  test/unit/ui_test.js
Labels: feature, ready for review, reporter:allure

#1986 Introduce scrollIntoView for WebDriver & Appium
  docs/helpers/Appium.md
  docs/helpers/WebDriver.md
  docs/webapi/scrollIntoView.mustache
  lib/helper/Appium.js
  lib/helper/WebDriver.js
  test/data/app/view/form/scroll_into_view.php
  test/helper/WebDriver_test.js
  typings/types.d.ts
Labels: appium, webdriver

#1962 introduce authentication for puppeteer
  lib/helper/Puppeteer.js
  lib/helper/WebDriver.js
  test/data/app/controllers.php
  test/data/app/index.php
  test/data/app/view/basic_auth.php
  test/helper/Puppeteer_test.js
  test/helper/WebDriver_test.js
Labels: puppeteer, ready for review, webdriver

#2125 fix(typings): seeTextEquals, detox, event, recorder and output
  docs/helpers/Detox.md
  docs/plugins.md
  docs/webapi/seeTextEquals.mustache
  lib/actor.js
  lib/container.js
  lib/event.js
  lib/helper/Protractor.js
  lib/helper/Puppeteer.js
  lib/helper/WebDriver.js
  lib/helper/clientscripts/nightmare.js
  lib/index.js
  lib/output.js
  lib/recorder.js
  lib/store.js
  lib/ui.js
  package.json
  runio.js
  test/runner/definitions_test.js
  typings/index.d.ts
  typings/jsdoc.conf.js
  typings/jsdoc.namespace.js
  typings/types.d.ts
Labels: ready for review, typescript

#2129 Release 2.4
  .github/workflows/check.yml
  .gitignore
  CHANGELOG.md
  docs/advanced.md
  docs/basics.md
  docs/bdd.md
  docs/commands.md
  docs/helpers/ApiDataFactory.md
  docs/helpers/Appium.md
  docs/helpers/FileSystem.md
  docs/helpers/GraphQL.md
  docs/helpers/GraphQLDataFactory.md
  docs/helpers/Mochawesome.md
  docs/helpers/MockRequest.md
  docs/helpers/Nightmare.md
  docs/helpers/Protractor.md
  docs/helpers/Puppeteer.md
  docs/helpers/REST.md
  docs/helpers/TestCafe.md
  docs/helpers/WebDriver.md
  docs/locators.md
  lib/command/run-rerun.js
  lib/helper/MockRequest.js
  lib/rerun.js
  package.json
  runio.js
  test/runner/definitions_test.js
  test/runner/run_rerun_test.js
  typings/types.d.ts
Labels: ✔️ has tests

#2134 Release 2.4.1
  CHANGELOG.md
  package.json
Labels: hotfix

#2139 Improvement parallel tests
  .travis.yml
  package.json
Labels: CI/CD, ready for review

#2145 (fix): wait for text instead of waiting for 2 secs
  test/acceptance/mock_test.js
Labels: CI/CD

#2156 (improvement): fix failed case
  test/acceptance/mock_test.js
Labels: ready for review

#2138 (improvement): Move unit tests to github actions
  .github/workflows/test.yml
  package.json
Labels: CI/CD, ready for review

#2146 (feat): add I say event to allure
  lib/plugin/allure.js
Labels: ready for review, reporter:allure

#2131 feat: Add selenoid plugin
  .gitignore
  examples/selenoid-example/browsers.json
  examples/selenoid-example/codecept.conf.js
  examples/selenoid-example/git_test.js
  lib/plugin/selenoid.js
Labels: plugin

#2147 (fix): ambiguous description on puppeteer helper
  lib/helper/Puppeteer.js
Labels: puppeteer, ready for review

#2140 (fix): npm audit throws vulnerability and screenshot unit tests error
  lib/plugin/screenshotOnFail.js
  package.json
Labels: ready for review

#2155 (fix): no custom output folder is created with run-worker
  lib/command/run-workers.js
  test/data/sandbox/codecept.workers-custom-output-folder-name.conf.js
  test/runner/run_workers_test.js
Labels: ready for review

#2164 improve file system helper
  docs/helpers/FileSystem.md
  lib/helper/FileSystem.js
  test/data/sandbox/configs/bootstrap/failed_test.js
  test/data/sandbox/configs/bootstrap/fs_test.js
  test/helper/Puppeteer_test.js
Labels: file helper
