Repository codeceptjs/CodeceptJS, pull requests merged in 2020-09, with the labels that each got.

#2559 Action Api Updated for dragSlider method
  lib/helper/WebDriver.js
Labels: bug

#2518 feat(timeout): Added timeouts for steps
  .mocharc.js
  lib/actor.js
  lib/config.js
  lib/recorder.js
  lib/step.js
  package.json
  test/data/sandbox/configs/steps/codecept-2000.conf.js
  test/data/sandbox/configs/steps/codecept-500.conf.js
  test/data/sandbox/configs/steps/customHelper.js
  test/data/sandbox/configs/steps/first_test.js
  test/runner/allure_test.js
  test/runner/consts.js
  test/runner/interface_test.js
  test/runner/steps_test.js
  test/unit/actor_test.js
  test/unit/worker_test.js
Labels: feature, timeouts

#2554 clean code
  lib/actor.js
  lib/assert/empty.js
  lib/assert/equal.js
  lib/assert/include.js
  lib/assert/truth.js
  lib/codecept.js
  lib/command/configMigrate.js
  lib/command/definitions.js
  lib/command/dryRun.js
  lib/command/gherkin/init.js
  lib/command/gherkin/snippets.js
  lib/command/gherkin/steps.js
  lib/command/info.js
  lib/command/init.js
  lib/command/interactive.js
  lib/command/list.js
  lib/command/run-multiple.js
  lib/command/run-rerun.js
  lib/command/run.js
  lib/container.js
  lib/data/context.js
  lib/event.js
  lib/helper/Appium.js
  lib/helper/FileSystem.js
  lib/helper/Mochawesome.js
  lib/helper/Nightmare.js
  lib/helper/Playwright.js
  lib/helper/Protractor.js
  lib/helper/clientscripts/PollyWebDriverExt.js
  lib/hooks.js
  lib/interfaces/gherkin.js
  lib/listener/helpers.js
  lib/listener/mocha.js
  lib/locator.js
  lib/pause.js
  lib/plugin/allure.js
  lib/plugin/autoDelay.js
  lib/plugin/autoLogin.js
  lib/plugin/standardActingHelpers.js
  lib/recorder.js
Labels: polish code

#2582 fix(#2579): say and retry methods now work correctly
  lib/container.js
Labels: 3.0
