Repository codeceptjs/CodeceptJS, pull requests merged in 2020-11, with the labels that each got.

#2651 docs: updates
  README.md
  docs/helpers/Playwright.md
  docs/helpers/Puppeteer.md
  docs/plugins.md
  lib/helper/Playwright.js
Labels: documentation, ready for review

#2658 Autologin workers
  lib/command/workers/runTests.js
Labels: ready for review

#2655 fix --suites flag for run workers
  lib/workers.js
  test/runner/run_workers_test.js
Labels: ready for review

#2611 (improvement): set maxUploadFileSize when performing api calls
  lib/helper/REST.js
  package.json
  test/data/rest/testUpload.json
  test/rest/REST_test.js
Labels: REST, ready for review

#2698 feat: Ensure skipped data driven tests have a skip entry per data entry
  lib/data/context.js
  test/data/sandbox/codecept.skip_ddt.json
  test/data/sandbox/ddt_test.skip_ddt.js
  test/runner/interface_test.js
Labels: ✔️ has tests
