Repository codeceptjs/CodeceptJS, pull requests merged in 2020-04, with the labels that each got.

#2308 (fix): undefined in screenshot name
  lib/plugin/screenshotOnFail.js
  test/unit/plugin/screenshotOnFail_test.js
Labels: plugin, ✔️ has tests

#2313 update waitForElement to support waitUntil in webdriverio^6.0
  lib/helper/WebDriver.js
Labels: webdriver

#2307 (fix): some typos in custom-helpers.md
  docs/custom-helpers.md
Labels: documentation

#2312 Fixed screenshot on failure for active session of WebDriver
  lib/helper/WebDriver.js
  lib/plugin/screenshotOnFail.js
  lib/session.js
  test/acceptance/codecept.Playwright.js
  test/acceptance/codecept.Puppeteer.js
  test/acceptance/codecept.WebDriver.js
  test/acceptance/session_test.js
  test/unit/plugin/screenshotOnFail_test.js
Labels: ✔️ has tests

#2296 (enh): Introduce yaml config file for semaphore 2.0
  .semaphore/semaphore.yml
  package.json
Labels: CI/CD

#2329 (docs): update playwright docs for how to use the waitForNavigation
  lib/helper/Playwright.js
Labels: documentation, playwright

#2327 #2321 - Modified the allure.js to support for custom runners
  lib/plugin/allure.js
Labels: ready for merging

#2319 (fix): wdio plugin issue with wdio v6
  lib/helper/WebDriver.js
  lib/plugin/wdio.js
Labels: plugin, webdriver

#2325 (Deprecated): drop WebDriverIO v4 helper
  .github/CONTRIBUTING.md
  README.md
  docker/README.md
  docs/books.md
  docs/custom-helpers.md
  docs/docker.md
  docs/hooks.md
  docs/visual.md
  examples/codecept.conf.example.js
  lib/helper/Protractor.js
  lib/helper/SeleniumWebdriver.js
  lib/helper/WebDriver.js
  lib/helper/WebDriverIO.js
  lib/plugin/standardActingHelpers.js
  runio.js
  test/acceptance/codecept.WebDriverIO.js
  test/helper/Nightmare_test.js
  test/helper/WebDriverIO_test.js
  test/unit/ui_test.js
Labels: 3.0

#2356 fix(workers): If fail scenario with same name, but diff feature - shows negative result
  lib/command/run-workers.js
  lib/command/workers/runTests.js
  test/data/sandbox/configs/workers/codecept.workers-negative.conf.js
  test/data/sandbox/workers/negative_results/negative1.workers.js
  test/data/sandbox/workers/negative_results/negative2.workers.js
  test/runner/run_workers_test.js
Labels: ready for merging, ready for review

#2357 updated to Plawyright 0.13, added handleDownloads
  lib/helper/Playwright.js
  package.json
  test/helper/Playwright_test.js
Labels: ✔️ has tests

#2231 Improve Scenario DX
  .circleci/config.yml
  .github/workflows/test.yml
  README.md
  docs/webapi/waitForVisible.mustache
  lib/command/definitions.js
  lib/command/run-workers.js
  lib/command/workers/runTests.js
  lib/helper/Playwright.js
  lib/helper/Puppeteer.js
  lib/helper/extras/PlaywrightPropEngine.js
  lib/parser.js
  lib/plugin/commentStep.js
  lib/scenario.js
  lib/workers.js
  package.json
  test/acceptance/config_test.js
  test/acceptance/mock_test.js
  test/acceptance/react_test.js
  test/acceptance/session_test.js
  test/acceptance/within_test.js
  test/data/inject-fail-example/first_test.js
  test/data/sandbox/base_test_session.js
  test/data/sandbox/base_test_within.js
  test/data/sandbox/browser_test.multiple.js
  test/data/sandbox/configs/allure/before_suite_test_failed.js
  test/data/sandbox/configs/allure/failed_ansi_test.js
  test/data/sandbox/configs/allure/success_test.js
  test/data/sandbox/configs/bootstrap/failed_test.js
  test/data/sandbox/configs/bootstrap/fs_test.js
  test/data/sandbox/configs/bootstrap/invalid_require_test.js
  test/data/sandbox/configs/commentStep/first_test.js
  test/data/sandbox/configs/pageObjects/first_test.js
  test/data/sandbox/configs/run-rerun/first_ftest.js
  test/data/sandbox/configs/run-rerun/first_test.js
  test/data/sandbox/custom-worker/base_test.worker.js
  test/data/sandbox/custom-worker/custom_test.worker.js
  test/data/sandbox/custom-worker/share_test.worker.js
  test/data/sandbox/ddt_test.addt.js
  test/data/sandbox/ddt_test.ddt.js
  test/data/sandbox/ddt_test.gddt.js
  test/data/sandbox/flaky_test.retry.js
  test/data/sandbox/flaky_test.retryFailed.js
  test/data/sandbox/fs_test.glob.js
  test/data/sandbox/fs_test.js
  test/data/sandbox/fs_test.po.js
  test/data/sandbox/fs_test_failed.js
  test/data/sandbox/grep_test.multiple.js
  test/data/sandbox/testevents_test.testevents.js
  test/data/sandbox/testhooks_test.testhooks.different.order.js
  test/data/sandbox/testhooks_test.testhooks.js
  test/data/sandbox/tests_test_override.multiple.js
  test/data/sandbox/testscenario_test.testscenario.js
  test/data/sandbox/workers/base_test.workers.js
  test/data/sandbox/workers/failing_test.worker.js
  test/data/sandbox/workers/test_grep.workers.js
  test/runner/definitions_test.js
  test/runner/interface_test.js
  test/unit/parser_test.js
  typings/index.d.ts
Labels: 3.0, feature, ready for review
