Repository codeceptjs/CodeceptJS, pull requests merged in 2020-07, with the labels that each got.

#2481 tests(step-log): Custom pretty logs for method args
  test/data/sandbox/configs/pageObjects/codecept.logs.json
  test/data/sandbox/configs/pageObjects/customHelper.js
  test/data/sandbox/configs/pageObjects/fs_test.logs.js
  test/data/sandbox/configs/pageObjects/pages/logs_page.js
  test/runner/pageobject_test.js
Labels: feature_request

#2474 add missing REST helper
  lib/plugin/standardActingHelpers.js
Labels: REST, plugin

#2513 fix no screenshot for failed tests
  lib/plugin/autoDelay.js
  lib/plugin/standardActingHelpers.js
Labels: bug
