Repository codeceptjs/CodeceptJS, pull requests merged in 2020-02, with the labels that each got.

#2178 fix: puppeteer basic auth fix
  lib/helper/Puppeteer.js
  test/helper/Puppeteer_test.js
Labels: bug, puppeteer

#2172 Update definitions.js to fix @bad slash in steps.d.ts bug typescript
  lib/command/definitions.js
Labels: bug, typescript

#2187 Fix: Add deepMerge to selenoid options
  lib/plugin/selenoid.js
Labels: bug, selenoid

#2184 fix(ts): add typing for Scenario.todo
  typings/index.d.ts
Labels: bug, ready for review, typescript

#2181 fix(Puppeteer): #waitForText - Cannot read property 'innerText' of null
  lib/helper/Puppeteer.js
  test/data/app/controllers.php
  test/data/app/index.php
  test/data/app/view/redirect_long.php
  test/helper/Puppeteer_test.js
Labels: bug, ready for review

#2173 [WIP] Playwright
  .github/workflows/playwright.yml
  .travis.yml
  docs/basics.md
  docs/changelog.md
  docs/helpers/Playwright.md
  docs/playwright.md
  lib/command/init.js
  lib/command/interactive.js
  lib/helper/Playwright.js
  package.json
  test/acceptance/codecept.Playwright.js
  test/acceptance/config_test.js
  test/acceptance/session_test.js
  test/acceptance/within_test.js
  test/helper/Playwright_test.js
  test/helper/webapi.js
Labels: playwright, ✔️ has tests

#2197 fix(mocha-ts): Fix conflicts with mocha and jest typings
  lib/container.js
  package.json
  typings/Mocha.d.ts
  typings/index.d.ts
Labels: bug, ready for review, typescript

#2179 Proper message for problem with addons
  lib/listener/helpers.js
Labels: enhancement

#2111 feat : Add grabCssPropertyFrom method for Nightmare
  lib/helper/Nightmare.js
  test/helper/webapi.js
Labels: 3.0

#1807 Remove default script timeout config.
  lib/helper/WebDriver.js
Labels: 3.0, appium, webdriver

#1830 CSS check to include `[` to determine if locator is CSS or not
  lib/locator.js
Labels: 3.0
