Repository codeceptjs/CodeceptJS, pull requests merged in 2023-07, with the labels that each got.

#3711 fix: screenshots every session for easy debugging
  lib/helper/Playwright.js
  lib/helper/Puppeteer.js
  lib/plugin/screenshotOnFail.js
Labels: plugin

#3689 feat(ci): add weekly dependabot
  .github/dependabot.yml
Labels: CI/CD

#3691 fix: handle importing custom helper nicely
  lib/container.js
Labels: typescript

#3729 fix(docs): mention AI feats
  README.md
Labels: documentation

#3704 fix: try out docker image push by tags
  .github/workflows/docker.yml
Labels: CI/CD

#3770 release 3.5.3
  CHANGELOG.md
  package.json
Labels: release

#3780 fix: remove bot users in contributors
  README.md
  package.json
  runok.js
Labels: bug

#3778 Fix enable highlight element
  docs/helpers/Playwright.md
  docs/helpers/Puppeteer.md
  docs/helpers/WebDriver.md
  lib/helper/Playwright.js
  lib/helper/Puppeteer.js
  lib/helper/WebDriver.js
Labels: bug, puppeteer, webdriver, playwright
